[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
async-h1 = {optional = true, version = "2.3.4"}
async-native-tls = {optional = true, version = "0.5.0"}
bevy = { version = "0.17.2", optional = true, features=["default_no_std", "serialize"], default-features=false }
http-types = {optional = true, version = "2.12.0"}
lightyear = "0.25.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_bytes = "0.11.19"
smol = { optional = true, version = "2.0.2"}

[features]
bevy = ["dep:bevy", "dep:smol", "dep:async-h1", "dep:async-native-tls", "dep:http-types"]
